version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JMX_PORT: '9999'
    ports:
      - '2181:2181'
    networks:
      - kafka-network
  kafka-broker:
    depends_on:
      - zookeeper
    image: bitnami/kafka:latest
    hostname: kafka-broker
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      UNCLEAN_LEADER_ELECTION_ENABLED: 'true'
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLED: 'true'
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION_ENABLED: 'true'
      JMX_PORT: '9999'
    ports:
      - '9092:9092'
    networks:
      - kafka-network
  eagle:
    depends_on:
      - zookeeper
    build:
      context: ./kafka-eagle
      args:
        ZK_HOSTS: zookeeper:2181
        WEB_PORT: '8484'
    ports:
      - '8484:8484'
    networks:
      - kafka-network
networks:
  kafka-network:
    external:
      name: cluster-network